name: Unit Test

env:
  GOVERSION: '1.17'
  GOMOD_CACHE_NAME: 'go-cache'

on:
  push:
    branches: [ master ]
  pull_request:
    branches-ignore: []

jobs:
  gomod:
    name: Resolve go module dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVERSION }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-

    - name: Download go module
      run: go mod download

    - name: Download go module for test
      run: cd test && go mod download

    - name: Build tools for go module caching
      run: make tools


  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs:
      - gomod
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVERSION }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-

    - name: Test
      run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - gomod
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOVERSION }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.GOMOD_CACHE_NAME }}-

    - name: Lint
      run: make lint-ci
